name: CI

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-timeout pytest-cov pylint flake8 black

    - name: Run linters
      run: |
        echo "Checking explorica.interactions with Pylint..."
        PYTHONPATH=src pylint src/explorica/interactions --max-line-length=88
        echo "Checking explorica.interactions with Flake8..."
        flake8 src/explorica/interactions --max-line-length=88
        echo "Checking explorica.interactions format with Black..."
        black --check src/explorica/interactions

        echo "Checking explorica.data_quality with Pylint..."
        PYTHONPATH=src pylint src/explorica/data_quality --max-line-length=88
        echo "Checking explorica.data_quality with Flake8..."
        flake8 src/explorica/data_quality --max-line-length=88
        echo "Checking explorica.data_quality format with Black..."
        black --check src/explorica/data_quality

        echo "Checking explorica._utils with Pylint..."
        PYTHONPATH=src pylint src/explorica/_utils --max-line-length=88
        echo "Checking explorica._utils with Flake8..."
        flake8 src/explorica/_utils --max-line-length=88
        echo "Checking explorica._utils format with Black..."
        black --check src/explorica/_utils
    - name: Run tests
      run: pytest --cov=explorica --maxfail=1
